trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerName: 'designsystem.storefront'

resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline.templates

stages:
  - stage: build
    displayName: Build, test and push container
    jobs:
      - template: docker/build-and-publish-container.yml@templates
        parameters:
          containerName: $(containerName)
          dockerfilePath: CI/Dockerfile
          arguments: '--build-arg APP_NAME=storefront'