name: Build Storefront
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/storefront/**'
jobs:
  checks:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use node 20 and yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn dlx turbo build --filter="./packages/*"
      - name: Build storefront
        run: yarn dlx turbo dev --filter=@apps/storefront
      - name: Types
        run: yarn types:storefront

