name: Checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'plugins/**'
      - 'biome.jsonc'
jobs:
  checks:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Lint code
        run: yarn biome ci .
